<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>CM_Task.TestsCore</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentAssertions" Version="8.10.0" />
      <PackageReference Include="NSubstitute" Version="5.3.0" />
      <PackageReference Include="xunit" Version="2.9.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CM-Task.Application\CM-Task.Application.csproj" />
      <ProjectReference Include="..\CM-Task.Domain\CM-Task.Domain.csproj" />
    </ItemGroup>

</Project>
